sonar.projectKey=ims-project
sonar.organization=rashi228
sonar.python.version=3.11
sonar.sources=backend/app,frontend/src
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.exclusions=backend/tests/**
sonar.cpd.exclusions=frontend/src/**/*,backend/app/**/*
