"""Add profile and approval fields

Revision ID: 7b7340993a6e
Revises: 5c2a1bb272e8
Create Date: 2026-06-13 07:37:20.584762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7340993a6e'
down_revision: Union[str, None] = '5c2a1bb272e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.String(), nullable=True))
    op.add_column('users', sa.Column('employee_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('area_of_expertise', sa.String(), nullable=True))
    op.add_column('users', sa.Column('approval_status', sa.String(), nullable=False))
    op.add_column('users', sa.Column('rejection_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rejection_reason')
    op.drop_column('users', 'approval_status')
    op.drop_column('users', 'area_of_expertise')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'employee_id')
    op.drop_column('users', 'department')
    # ### end Alembic commands ###
